/*  MY NAME=JOHN F KENNEDY MY ID=JFK63
		
		CORRECT OUTPUT 5 PTS	 CORRECT EXPLANATION 2 POINTS
--------------------------------------------------------------------------
MYSTERY #1:  <output=951413>	<It prints the number backwards>
MYSTERY #2:  <OUTPUT ANSWER HERE>	<Sums up the digits of the number>
MYSTERY #3:  <OUTPUT ANSWER HERE>	<YOUR EXPLANATION ANSWER HERE>
MYSTERY #4:  <OUTPUT ANSWER HERE>	<YOUR EXPLANATION ANSWER HERE>
MYSTERY #5:  <OUTPUT ANSWER HERE>	<YOUR EXPLANATION ANSWER HERE>
MYSTERY #6:  <OUTPUT ANSWER HERE>	<YOUR EXPLANATION ANSWER HERE>
MYSTERY #7:  <OUTPUT ANSWER HERE>	<YOUR EXPLANATION ANSWER HERE>
*/
